### ISSUE TITLE
support for REJSON 

### ISSUE THREAD

**Issue by x-077** [redis/ioredis#1055]
Hello @luin , 

Do you plan to add the support of the command for [REJSON](https://oss.redislabs.com/redisjson/) product from RedisLab ?

For now I using `call` method, it works fine but if we would have them included it would be great. 

Thanks

**Comment by budarin** [comment]
have a look at [iojson](https://github.com/evanhuang8/iorejson)

**Comment by matth-c3** [comment]
Hello @budarin , 


I use the following for quite some time now : 

```
....
const redis = require('ioredis');
const rUtils = require('ioredis/built/utils/index');
...


const addCommand = {
  xgroup:(target) => target.Command.setReplyTransformer('xgroup', (reply) => reply),
  xadd:(target) => target.Command.setReplyTransformer('xadd', (reply) => reply),
  xread:(target) => target.Command.setReplyTransformer('xread', parseStreamResponse),
  xpending:(target) => target.Command.setReplyTransformer('xpending', (reply) => {
    if (!reply || reply.length === 0)
      return [];
    if (reply.length === 4 && !isNaN(reply[0]))
      return {
        count:parseInt(reply[0]),
        minId:reply[1],
        maxId:reply[2],
        consumers:(reply[3] || []).map((consumer) => {
          return {
            name:consumer[0],
            count:parseInt(consumer[1])
          };
        })
      };
    return reply.map((message) => {
      return {
        id:message[0],
        consumerName:message[1],
        elapsedMilliseconds:parseInt(message[2]),
        deliveryCount:parseInt(message[3])
      };
    });
  }),
  xreadgroup:(target) => target.Command.setReplyTransformer('xreadgroup', parseStreamResponse),
  xrange:(target) => target.Command.setReplyTransformer('xrange', parseMessageResponse),
  xrevrange:(target) => target.Command.setReplyTransformer('xrevrange', parseMessageResponse),
  xclaim:(target) => target.Command.setReplyTransformer('xclaim', parseMessageResponse),
  xinfo:(target) => target.Command.setReplyTransformer('xinfo', (reply) => parseObjectResponse(reply, (key, value) => {
    switch (key) {
      case 'first-entry':
      case 'last-entry':
        if (!Array.isArray(value))
          return value;
        return {
          id:value[0],
          data:parseObjectResponse(value[1])
        };
      default:
        return value;
    }
  })),
  xack:(target) => target.Command.setReplyTransformer('xack', (reply) => parseInt(reply)),
  xlen:(target) => target.Command.setReplyTransformer('xlen', (reply) => parseInt(reply)),
  xtrim:(target) => target.Command.setReplyTransformer('xtrim', (reply) => parseInt(reply)),
  xdel:(target) => target.Command.setReplyTransformer('xdel', (reply) => parseInt(reply))
};

const parseObjectResponse = (reply, customParser = null) => {
  if (!Array.isArray(reply))
    return reply;
  const data = {};
  for (let i = 0; i < reply.length; i += 2) {
    if (customParser) {
      data[reply[i]] = customParser(reply[i], reply[i+1]);
      continue;
    }
    data[reply[i]] = reply[i+1];
  }
  return data;
};

const parseMessageResponse = (reply) => {
  if (!Array.isArray(reply))
    return [];
  return reply.map((message) => {
    return {id:message[0], data:parseObjectResponse(message[1])};
  });
};

const parseStreamResponse = (reply) => {
  if (!Array.isArray(reply))
    return reply;
  const object = {};
  for (const stream of reply)
    object[stream[0]] = parseMessageResponse(stream[1]);
  return object;
};

Object.keys(addCommand).forEach((command) => {
  const {string, buffer} = redis.prototype.createBuiltinCommand(command);
  redis.prototype[command] = string;
  redis.prototype[command+'Buffer'] = buffer;
  addCommand[command](redis);
});

redis.Command.setArgumentTransformer('xadd', function (args) {
  if (args.length === 3) {
    if (typeof args[2] === 'object') {
      return [args[0],args[1]].concat(rUtils.convertObjectToArray(args[2]));
    }
  }
  return args;
});

const conn = new redis( ....

```

**Comment by budarin** [comment]
Hi @matth-c3 

the code above not for using JSON commands from REJSON (

**Comment by matth-c3** [comment]
Hello  @budarin , sorry, you are right, wrong part :D the version that I used of ioredis did not implement streams at that time.

it could be possible to add them using createBuiltinCommand or maybe inspire from the [following ](https://github.com/evanhuang8/iorejson) to have them natively in ioredis ?

I can not upgrade version as `call` would not work anymore :/

Thanks

**Comment by matth-c3** [comment]
@budarin any chance that you see my previous update ?

Thanks

**Comment by budarin** [comment]
@matth-c3 I'm sorry - i'm busy with another task - i'll look at when I work with redis

**Comment by nidomiro** [comment]
I had the same problem while searching for a lib to handle RedisJson. The `call` method was renamed.
Here is a working example:
```typescript
import * as IORedis from "ioredis";
const redis = new IORedis();

function printWithType(v: unknown) {
  console.log("---")
  console.log("Type: ", typeof v)
  console.log("Value: ", v)
  console.log("---")
}

redis.send_command("JSON.SET", "my:key", ".",  '{"id": "abc", "groups": ["A", "B", "C"]}')
  .then(printWithType)
  .catch(e => (console.error(e)))

redis.send_command("JSON.GET", "my:key")
  .then(printWithType)
  .catch(e => (console.error(e)))

redis.send_command("JSON.GET", "my:key", ".id")
  .then(printWithType)
  .catch(e => (console.error(e)))

redis.send_command("JSON.GET", "my:key", ".groups")
  .then(printWithType)
  .catch(e => (console.error(e)))
```

The output is:
```
---
Type:  string
Value:  OK
---
---
Type:  string
Value:  {"id":"abc","groups":["A","B","C"]}
---
---
Type:  string
Value:  "abc"
---
---
Type:  string
Value:  ["A","B","C"]
---
```

**Comment by OmarOmeiri** [comment]
> ```ts
> redis.send_command("JSON.SET", "my:key", ".",  '{"id": "abc", "groups": ["A", "B", "C"]}')
>   .then(printWithType)
>   .catch(e => (console.error(e)))
> 
> redis.send_command("JSON.GET", "my:key")
>   .then(printWithType)
>   .catch(e => (console.error(e)))
> 
> redis.send_command("JSON.GET", "my:key", ".id")
>   .then(printWithType)
>   .catch(e => (console.error(e)))
> 
> redis.send_command("JSON.GET", "my:key", ".groups")
>   .then(printWithType)
>   .catch(e => (console.error(e)))
> ```

Why do I get errors? all commands are unknown for me. using the same code you provided with Node 16.x?

```
ReplyError: ERR unknown command 'JSON.SET'
    at parseError (E:\Documents\CODE\WebDev\Lullo\backend\src\node_modules\redis-parser\lib\parser.js:179:12)
    at parseType (E:\Documents\CODE\WebDev\Lullo\backend\src\node_modules\redis-parser\lib\parser.js:302:14) {
  command: {
    name: 'JSON.SET',
    args: [ 'my:key', '.', '{"id": "abc", "groups": ["A", "B", "C"]}' ]
  }
}
ReplyError: ERR unknown command 'JSON.GET'
    at parseError (E:\Documents\CODE\WebDev\Lullo\backend\src\node_modules\redis-parser\lib\parser.js:179:12)
    at parseType (E:\Documents\CODE\WebDev\Lullo\backend\src\node_modules\redis-parser\lib\parser.js:302:14) {
  command: { name: 'JSON.GET', args: [ 'my:key' ] }
}
ReplyError: ERR unknown command 'JSON.GET'
    at parseError (E:\Documents\CODE\WebDev\Lullo\backend\src\node_modules\redis-parser\lib\parser.js:179:12)
    at parseType (E:\Documents\CODE\WebDev\Lullo\backend\src\node_modules\redis-parser\lib\parser.js:302:14) {
  command: { name: 'JSON.GET', args: [ 'my:key', '.id' ] }
}
ReplyError: ERR unknown command 'JSON.GET'
    at parseError (E:\Documents\CODE\WebDev\Lullo\backend\src\node_modules\redis-parser\lib\parser.js:179:12)
    at parseType (E:\Documents\CODE\WebDev\Lullo\backend\src\node_modules\redis-parser\lib\parser.js:302:14) {
  command: { name: 'JSON.GET', args: [ 'my:key', '.groups' ] }
}
```

**Comment by PavelPashov** [comment]
Closing this as there's an existing example of using the JSON module [here](https://github.com/redis/ioredis/blob/main/examples/module.js)
