### ISSUE TITLE
Using docker-compose & redis on nodejs

### ISSUE THREAD

**Issue by Kristoffer95** [redis/ioredis#1121]
**I am following this tutorial: h[ttps://youtu.be/th-KXdI8HDU?list=PLcCp4mjO-z9_HmJ5rSonmiEGfP-kyRMlI&t=868](https://youtu.be/th-KXdI8HDU?list=PLcCp4mjO-z9_HmJ5rSonmiEGfP-kyRMlI&t=868)**

Using ts-node version 8.10.1, typescript version 3.8.3
http://localhost:3000
```
[ioredis] Unhandled error event: Error: write EPIPE
    at WriteWrap.afterWrite (net.js:789:14)
[ioredis] Unhandled error event: Error: write EPIPE
    at WriteWrap.afterWrite (net.js:789:14)
[ioredis] Unhandled error event: Error: write EPIPE
    at WriteWrap.afterWrite (net.js:789:14)
[ioredis] Unhandled error event: Error: write EPIPE
    at WriteWrap.afterWrite (net.js:789:14)
[ioredis] Unhandled error event: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
[ioredis] Unhandled error event: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
[ioredis] Unhandled error event: Error: write EPIPE
    at WriteWrap.afterWrite (net.js:789:14)
[ioredis] Unhandled error event: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
[ioredis] Unhandled error event: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
[ioredis] Unhandled error event: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
[ioredis] Unhandled error event: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
```

**Comment by Adizbek** [comment]
Can you show your docker-compose.yml ?

**Comment by ulises-castro** [comment]
Hi, I was facing this issue and I was able to solve just changing my command line inside of the docker-compose file from:

```docker
version: '3.8'

services:
  redis:
    container_name: redis_container
    image: redis:6.0.7
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - redis_data:/var/lib/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
```
To this, and It can now connect to my dockerized redis from my host (computer)

```docker
services:
  redis:
    container_name: redis_container
    image: redis:6.0.7
    command: ['--requirepass "password"']  
    volumes:
      - redis_data:/var/lib/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
```
