### ISSUE TITLE
`undefined` key is treated as `''`

### ISSUE THREAD

**Issue by jmcdo29** [redis/ioredis#1652]
## Current Behavior

`ioredis` will treat a key of `undefined` the same as the key `''`, meaning you can call `redis.set(undefined, 'some value')` and later use `redis.get('')` to get `'some value'` from the redis instance. 

## Expected Behavior

`ioredis` either throws an error that `undefined` was passed when there should be an explicit string or Buffer, **or** it is documented that `ioredis` will automatically convert the `undefined` to `''`.

## Minimum Reproduction Repository

https://github.com/jmcdo29/ioredis-undefined-key

## Reproduction steps

```sh
git clone git@github.com:jmcdo29/ioredis-undefined-key.git
cd ioredis-undefined-key
pnpm i
docker compose up -d
node index.js
docker compose down
```

Observe the assertion failure from `notEqual()` in the `getBlankStringKey` method.

**Comment by dontbesatisfied** [comment]
same issue

`set(key, value, expiryMode, time, setMode)`

expiryMode, time, setMode are undefined

ReplyError: ERR syntax error
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'set',
    args: [
      'keyxxxxxxx,
      'valuexxxxxxxx',
      '',
      '',
      ''
    ]
  }

**Comment by dontbesatisfied** [comment]
any help?

**Comment by dontbesatisfied** [comment]
hello?

**Comment by luin** [comment]
Hey @jmcdo29 @dontbesatisfied 👋 

Yeah `undefined` and `null` are treated as empty strings so we should document it. We can change that in the next major version if there are good reasons.

**Comment by mariusaarsnes** [comment]
IMO it makes sense to differentiate between `undefined` and `null` as there is a semantic difference between the two values. 

In my case we have a `getOrSet` method which first checks if the value exists in the cache and if not it tries to fetch the value from a third party and stores it in the cache before returning the value. 
Here it makes sense to differentiate between `undefined` and `null`. An `undefined` value will indicate that there is nothing stored in the cache and we want to fetch from the database. A `null` value will indicate that nothing exists for the key being looked up (either in the cache or the third party).
