### ISSUE TITLE
ssubscribe within a cluster is not working properly

### ISSUE THREAD

**Issue by darrachequesne** [redis/ioredis#1759]
Hi! It seems there is an issue with the spublish()/ssubscribe() methods added in https://github.com/luin/ioredis/commit/6285e80ffb47564dc01d8e9940ff9a103bf70e2d:

```js
import { Cluster } from "ioredis";

const clusterNodes = [
  {
    host: "localhost",
    port: 7000,
  },
  {
    host: "localhost",
    port: 7001,
  },
  {
    host: "localhost",
    port: 7002,
  },
  {
    host: "localhost",
    port: 7003,
  },
  {
    host: "localhost",
    port: 7004,
  },
  {
    host: "localhost",
    port: 7005,
  },
];

const pubClient = new Cluster(clusterNodes);
const subClient = pubClient.duplicate();

subClient.ssubscribe("foo", () => {
  pubClient.spublish("foo", "bar");
});

subClient.on("smessage", (_, message) => {
  console.log("got", message); // never received
});
```

The `smessage` event is not received. It works with classic publish()/subscribe() though:

```js
subClient.subscribe("foo", () => {
  pubClient.publish("foo", "bar");
});

subClient.on("message", (_, message) => {
  console.log("got", message); // prints "got bar"
});
```

My `docker-compose.yml`, for reproducibility:

```yml
services:
  redis-cluster:
    image: grokzen/redis-cluster:7.0.10
    ports:
      - "7000-7005:7000-7005"
```

The test case [here](https://github.com/luin/ioredis/blob/7096a10665a72b6df3f6f6a312e07249a3690a66/test/functional/cluster/spub_ssub.ts#L24-L30) looks a bit weird, shouldn't it be something like:

```js
const pub = new Cluster(options);
const ssub = new Cluster(options);

ssub.ssubscribe("test cluster", function () {
  pub.spublish("test shard channel", "hi");

  // node1.write(node1.findClientByName("ioredis-cluster(subscriber)"), [
  //   "smessage",
  //   "test shard channel",
  //   "hi",
  // ]);
});
```

Thanks in advance!

**Comment by luin** [comment]
Thanks for raising this up! Yeah we currently don't route messages to the right node and also don't subscribe to the right node. Should think about a solution for that.

**Comment by NurimOnsemiro** [comment]
I'm facing the same problem, I'm not getting the 'smessage' event when I register the sSubscribe function.

**Comment by NurimOnsemiro** [comment]
With a total of 3 Redis servers (ports 6379, 6380, 6381) deployed in a Redis Cluster using Docker Compose, I executed the code below.

```typescript
import { Cluster, Redis } from 'ioredis'

async function getRedisClient(): Promise<Cluster> {
  return new Promise(async (resolve, reject) => {
    const redisClient = new Redis.Cluster([
      {
        host: 'localhost',
        port: 6379
      }
  ], {
      scaleReads: 'slave',
      retryDelayOnMoved: 100,
      redisOptions: {
        username: 'default',
        password: 'redispw',
        tls: undefined
      },
    })
    redisClient.on('error', (err: Error) => {
      console.error('[Ioredis] on ERROR', err)
    })
    redisClient.on('connect', async () => {
      console.log('Redis cluster connected')
      resolve(redisClient)
    })
  })
}

async function main() {
  const publisher = await getRedisClient()
  const subscriber = await getRedisClient()

  subscriber.on('smessage', (channel: string, message: string) => {
    console.log('smessage', channel, message)
  })

  subscriber.on('message', (channel: string, message: string) => {
    console.log('message', channel, message)
  })

  await subscriber.ssubscribe('hello1') // Too many redirection error (127.0.0.1:6380)
  await subscriber.ssubscribe('hello2') // Too many redirection error (127.0.0.1:6381)
  await subscriber.ssubscribe('hello3') // ok (127.0.0.1:6379)

  await publisher.spublish('hello3', '{"name": "honsemiro"}')
}
main()
```
Of these, only the 'hello3' channel was successful in subscribing to the shard channel. My guess is that there are different shards that are assigned based on the checksum value, and that's why it subscribes to certain shards and not others. Here's the error message.

```
Redis cluster connected
Redis cluster connected
c:\Users\<redacted>\Documents\nodejs\tsc_test_01\node_modules\ioredis\built\cluster\index.js:508
            handlers.maxRedirections(new Error("Too many Cluster redirections. Last error: " + error));
                                     ^
Error: Too many Cluster redirections. Last error: ReplyError: MOVED 11613 127.0.0.1:6381
    at EventEmitter.handleError (c:\Users\<redacted>\Documents\nodejs\tsc_test_01\node_modules\ioredis\built\cluster\index.js:508:38)
    at Command.command.reject (c:\Users\<redacted>\Documents\nodejs\tsc_test_01\node_modules\ioredis\built\cluster\index.js:362:23)
    at EventEmitter.handleReconnection (c:\Users\<redacted>\Documents\nodejs\tsc_test_01\node_modules\ioredis\built\Redis.js:509:30)
    at DataHandler.returnError (c:\Users\<redacted>\Documents\nodejs\tsc_test_01\node_modules\ioredis\built\DataHandler.js:41:20)
    at JavascriptRedisParser.returnError (c:\Users\<redacted>\Documents\nodejs\tsc_test_01\node_modules\ioredis\built\DataHandler.js:15:22)
    at JavascriptRedisParser.execute (c:\Users\<redacted>\Documents\nodejs\tsc_test_01\node_modules\redis-parser\lib\parser.js:542:14)
    at Socket.<anonymous> (c:\Users\<redacted>\Documents\nodejs\tsc_test_01\node_modules\ioredis\built\DataHandler.js:25:20)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:315:12)
```

**Comment by m4tty-d** [comment]
is there any updates on this? @luin 
are there any workarounds until this will be supported?

**Comment by tominou** [comment]
Any news about it ? I'd prefer not to migrate to `node-redis`.

**Comment by lstradella** [comment]
Hi,
Is this issue still open considering the new 5.6.0 ioredis release, which introduced "_Sharded pub/sub support via dedicated subscribers_"?

**Comment by vishnukumarya-kore** [comment]
https://github.com/redis/ioredis/pull/1967

Even the sharded pubsub changes are added in 4.29.1. Can you please check if this is supported now and update the documentation

**Comment by darrachequesne** [comment]
For future readers:  this was fixed by https://github.com/redis/ioredis/pull/1956, included in `ioredis@5.9.0`.

**Comment by notsapinho** [comment]
<img width="994" height="126" alt="Image" src="https://github.com/user-attachments/assets/a2ee62ec-c200-4aca-b87b-2b722499319f" />

https://socket.io/docs/v4/redis-adapter/#with-redis-sharded-pubsub

This should be removed then.

**Comment by darrachequesne** [comment]
@notsapinho good catch, thanks! The warning has been removed.
