### ISSUE TITLE
error events missing data

### ISSUE THREAD

**Issue by pvogel1967** [redis/ioredis#1780]
I had a weird issue in my repo when moving to node 18 (from 16) where localhost seems to have been resolving to an IPV6 address instead of the IPv4 127.0.01 -- with the `'error'` event handler commented out, I would get this:

```
[ioredis] Unhandled error event: ClusterAllFailedError: Failed to refresh slots cache.
    at tryNode (.../node_modules/ioredis/built/cluster/index.js:308:31)
    at .../node_modules/ioredis/built/cluster/index.js:325:21
    at .../node_modules/ioredis/built/cluster/index.js:662:24
    at run (.../node_modules/ioredis/built/utils/index.js:117:22)
    at tryCatcher (.../node_modules/standard-as-callback/built/utils.js:12:23)
    at .../node_modules/standard-as-callback/built/index.js:33:51
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Which at least got me on the right track, turning on DEBUG='ioredis:*' got me the rest of the way...

```
  ioredis:cluster resolved hostname localhost to IP ::1 +98ms
  ioredis:cluster:connectionPool Reset with [ { host: '::1', port: 12000 } ] +0ms
  ioredis:cluster:connectionPool Connecting to ::1:12000 as master +0ms
  ioredis:redis status[::1:12000]: wait -> wait +0ms
  ioredis:cluster getting slot cache from ::1:12000 +1ms
  ioredis:redis status[::1:12000 (ioredis-cluster(refresher))]: wait -> wait +0ms
  ioredis:redis status[::1:12000 (ioredis-cluster(refresher))]: wait -> connecting +0ms
  ioredis:redis queue command[::1:12000 (ioredis-cluster(refresher))]: 0 -> cluster([ 'SLOTS' ]) +0ms
  ioredis:cluster:subscriber selected a subscriber ::1:12000 +0ms
  ioredis:redis status[::1:12000 (ioredis-cluster(subscriber))]: wait -> wait +1ms
  ioredis:cluster:subscriber started +0ms
  ioredis:connection error: Error: connect ECONNREFUSED ::1:12000
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at __node_internal_exceptionWithHostPort (node:internal/errors:668:12)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 12000
} +0ms
  ioredis:redis status[::1:12000 (ioredis-cluster(refresher))]: connecting -> close +1ms
  ioredis:connection skip reconnecting because `retryStrategy` is not a function +0ms
  ioredis:redis status[::1:12000 (ioredis-cluster(refresher))]: close -> end +0ms
```

But I wasted *a ton* of time because with an error handler in place:

```
        this._redis.on('error', (redisError, arg2, arg3) => {
            if (redisError.code === 'ECONNREFUSED') {
                if (redisError.address === '127.0.0.1') {
                    logger.error(
                        { redisError },
                        'Redis connection error. Did you run `yarn local:up` from the repo root?',
                    );
                } else {
                    logger.error({ redisError }, 'Redis connection error.');
                }
            } else {
                logger.error({ arg1: redisError, code: redisError.code, arg2, arg3 }, 'Unrecognized Redis error.');
            }
        });
```

I get this (note: no code, no arg2, arg3).
```
[2023-07-08T00:03:53.663Z] ERROR: Unrecognized Redis error.
    arg1: {
      "lastNodeError": {}
    }
```

Since this was, in fact, an ECONNREFUSED problem, I should have had a redisError with a code, etc. or should _at least_ have seen something similar in the lastNodeError instead of an empty object...

looking (briefly) at the ioredis code for where the `error` event is emitted, it's the `silentEmit` function in lib/Redis.ts, where I see this:
```
      return this.emit.apply(this, arguments);
```
But `arguments` isn't set anywhere that I can see in `silentEmit`, the params to silentEmit are `eventName` and `arg`.  Should that line be, perhaps, `return this.emit.apply(this, arg);`?

**Comment by pvogel1967** [comment]
Just realized I forgot about `arguments` being available in functions as an array of all incoming args.  So my diagnosis is clearly incorrect, yet there is obviously an issue here since no useful info is coming in to the error handler
