### ISSUE TITLE
pipeline error:  [[],[],[]] not working  

### ISSUE THREAD

**Issue by F-Y-M** [redis/ioredis#1799]
``OS: WINDOWS 10 22H12
NODE: V18.16.1
REDIS-STACK: 7.2.0
IOREDIS: 5.3.2

issue: 
trying to create with hmset a pipeline having this structure

userService.createMany: 
```

const createMany = async ({data}) => {
    console.log(data)
    let commands = data.map(user => {
        let command = [Object.entries(user).flat()]
        command[0].unshift('hmset')
        return command.flat()
    });

    console.log("commands: ", commands)

    try {
        const result = await redis.pipeline(commands)
            .exec( (err, result) => {
                if(err) throw new Error('debes agregar usuarios validos')
                else return result
            })
        console.log("result: ", result)
    } catch (error) {
        console.log("ERROR: ", error )
    }
}
```
main.js

```
const data = [
          {
            id: String(13),
            name: 'jhon',
            surname: 'quiñones',
            specialties: JSON.stringify(['cirujano-plastico','dentista','fisico-culturista']),
            fee: JSON.stringify([22000,34000,1800000]),
            rate: String(4),
            calendar: JSON.stringify([
              '0::cita-medica::2023-08-16/17:00::2023-08-16/17:30::true::green',
              '1::cita-medica::2023-08-17/16:00::2023-08-17/16:30::false::red',
              '2::cita-medica::2023-08-18/17:00::2023-08-18/17:30::true::green',
            ])
          }
          ,
          {
            id: String(10),
            name: 'maria',
            surname: 'la-del-barrio',
            specialties: JSON.stringify(['contadora','otorrinonaringologa','nadadora']),
            fee: JSON.stringify([22000,34000,1800000]),
            rate: String(5),
            calendar: JSON.stringify([
              '0::cita-medica::2023-08-16/17:00::2023-08-16/17:30::true::green',
              '1::cita-medica::2023-08-17/16:00::2023-08-17/16:30::false::red',
              '2::cita-medica::2023-08-18/17:00::2023-08-18/17:30::true::green',
            ])
          }
        ]
        
await createMany({data}))
```

response: 

result:  [
  [
    ReplyError: ERR wrong number of arguments for 'hmset' command
        at parseError (C:\Users\user\Documents\proyects\redis\node_modules\redis-parser\lib\parser.js:179:12)
        at parseType (C:\Users\user\Documents\proyects\redis\node_modules\redis-parser\lib\parser.js:302:14) {
      command: [Object]
    }
  ],
  [
    ReplyError: ERR wrong number of arguments for 'hmset' command
        at parseError (C:\Users\user\Documents\proyects\redis\node_modules\redis-parser\lib\parser.js:179:12)
        at parseType (C:\Users\user\Documents\proyects\redis\node_modules\redis-parser\lib\parser.js:302:14) {
      command: [Object]
    }
  ]
]

steps to reproduce the error: 
1 create a redis instance
2 create an array with the commands and the key/value 
3 use pipeline(arr)

**Comment by F-Y-M** [comment]
solved:
i was trying to add an odd number of args, i just add a name after the command and works
